name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.5.3'

    - name: Install dependencies
      run: flutter pub get

    - name: Build macOS for arm64
      run: flutter build macos --release --dart-define=FLUTTER_TARGET_PLATFORM=darwin-arm64

    - name: Code Sign
      run: |
        sudo spctl --master-disable
        codesign --force --deep --sign - build/macos/Build/Products/Release/RustDesk.app
        sudo spctl --master-enable

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/macos/Build/Products/Release
